COLUMNS:
  date: object
  temp: float64
  precip: float64
  humidity: float64
  windspeed: float64
  cloudcover: float64
  dew: float64
  yesterday: float64
  today: float64
  year_month: object
  dollar_rate: float64

TARGET_COLUMN:
  name: today